version: '3.8'

services:
  db:
    image: mysql:latest 
    container_name: vaultify_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password  
      MYSQL_DATABASE: vaultify_dev   
      MYSQL_USER: vaultify_user  
      MYSQL_PASSWORD: vaultify_password  
    ports:
      - "3306:3306"   
    volumes:
      - ./data/mysql:/var/lib/mysql  
    restart: always
    networks:
      - vaultify_network

  phpmyadmin:
    image: phpmyadmin:latest 
    container_name: vaultify_phpmyadmin
    environment:
      PMA_HOST: db  
      PMA_PORT: 3306  
      PMA_ARBITRARY: 0
    ports:
      - "80:80"  
    restart: always
    depends_on:
      - db
    networks:
      - vaultify_network

networks:
  vaultify_network:
    driver: bridge